language: node_js
node_js:
    - '12'
    - '11'
    - '10'
    - '8'
cache:
    directories:
        - node_modules
script:
    - npm run bootstrap
    - npm run lint
    - npm run test
    - npm run build
